#!/usr/bin/env sh

# Exit immediately if any command fails
set -e
vcom myTypes.vhd
vcom fetch/ffd.vhd
vcom fetch/register_generic.vhd
vcom decode/ffd.vhd
vcom decode/register_generic.vhd
vcom decode/signExtend.vhd
vcom decode/RegisterFile.vhd
vcom fetch/rca.vhd
vcom fetch/fetch.vhd
vcom decode/decode.vhd
vcom exe/constants.vhd
vcom exe/myTypes.vhd
vcom exe/mux21generic.vhd
vcom exe/lfsr.vhd
vcom exe/fa.vhd
vcom exe/rca.vhd
vcom exe/csb.vhd
vcom exe/SumGenerator.vhd
vcom exe/pg.vhd
vcom exe/g.vhd
vcom exe/pg_generator.vhd
vcom exe/CLA_SPARSE_TREE.vhd
vcom exe/xor.vhd
vcom exe/P4_ADDER.vhd
vcom exe/ctrl_alu.vhd
vcom exe/logic_and_shift.vhd
vcom exe/comparator.vhd
vcom exe/outputSelect.vhd
vcom exe/alu_top.vhd 
vcom exe/ZERO_DET.vhd
vcom exe/ffd.vhd
vcom exe/register_generic.vhd
vcom exe/mux21generic.vhd
vcom exe/execute.vhd
vcom memory/constants.vhd
vcom memory/ffd.vhd
vcom memory/mux21.vhd
vcom memory/mux21generic.vhd
vcom memory/register_generic.vhd
vcom memory/memory.vhd
vcom wb/constants.vhd
vcom wb/mux21generic.vhd
vcom wb/WB.vhd
vcom datapath.vhd
vcom tb_datapath.vhd
vsim -do dofile_datapath.do